server:
  port: 0 # указывается 0, чтобы при регистрации сервиса eureka-server порт был определен автоматически
  #port: 8081
marketplace:
  feign-client:
    account-service:
      uri: http://localhost:8765/account-service
spring:
  application:
    name: catalog-service # id приложения - желательно указывать всегда в микросервисных приложениях
    gateway-host: http://localhost:8765
    add-to-cart-url: /account-service/account/{userId}/cart/{productId}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/marketplace # тот, кто выдает jwt
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/marketplace
        registration:
#          keycloak:
#            client-id: catalog-service
#            client-sercret: rYV6GRUFZ1ihZXV7lGUIg0GZWSP2WhEt
#            scope:
#              - openid
          discovery:
            provider: keycloak
            client-id: catalog-service
            client-secret: rYV6GRUFZ1ihZXV7lGUIg0GZWSP2WhEt
            authorization-grant-type: client_credentials
            scope:
              - discovery
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      product-rating: product-rating-topic
      favorites: new-favorite-topic
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace-catalog-db
    username: postgres
    password: My_passw0rd
  flyway:
    enabled: true # по умолчанию
    locations: classpath:db/migration # по умолчанию
    baseline-on-migrate: true
  jpa:
    open-in-view: false # если будет true, то после выхода из контроллера возможно открытие сессии hibernate
    properties:
      hibernate:
        show_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # url, куда будет происходить регистрация микросервисов
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${random.uuid} # чтобы каждый экземпляр микросервиса имел уникальный id
    # prefer-ip-address: true
logging:
  pattern:
    #console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n" # формат логов
  level:
    sql: info
    org.springframework.kafka.*: OFF
    org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: OFF
    org.apache.kafka.*: OFF
    kafka.*: OFF
    org.apache.zookeeper.*: OFF


