version: '3'
services:
  zookeeper:
    container_name: mpc-zookeeper
    image: zookeeper
    ports:
      - 22181:2181
  kafka:
    container_name: mpc-kafka
    image: apache/kafka
    ports:
      - '29092:9092'
    depends_on:
      - zookeeper

  eureka-server:
    container_name: mpc-eureka-server
    image: marketplace/eureka-server
    ports:
      - 8761:8761
  api-gateway:
    container_name: mpc-api-gateway
    image: marketplace/api-gateway
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
    restart: always
    depends_on:
      - eureka-server
    ports:
      - '8765:8765'

  postgres-account:
    container_name: mpc-account-db-postgres
    image: postgres:16rc1-alpine
    environment:
      POSTGRES_DB: mpc-account-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  account-service:
    container_name: mpc-account-service
    build:
      context: account-service/impl
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-account:5432/mpc-account-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - postgres-account
      - kafka

  postgres-catalog:
    container_name: mpc-catalog-db-postgres
    image: postgres:16rc1-alpine
    environment:
      POSTGRES_DB: mpc-catalog-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  catalog-service:
    container_name: mpc-catalog-service
    build:
      context: catalog-service/impl
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-catalog:5432/mpc-catalog-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - postgres-catalog
      - kafka

#  order-service:
#    container_name: mpc-order-service
#    build:
#      context: order-service/impl
#      dockerfile: Dockerfile
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
#    depends_on:
#      - postgres
#      - kafka
#
#  feedback-service:
#    container_name: mpc-feedback-service
#    build:
#      context: feedback-service/impl
#      dockerfile: Dockerfile
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
#    depends_on:
#      - postgres
#      - kafka
