version: '3'
services:

  postgres:
    container_name: mpc-account-db-postgres
    image: postgres:16rc1-alpine
    environment:
      #POSTGRES_DB: marketplace-catalog-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  application:
    container_name: mpc-account-service
    build:
      context: impl
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - kafka